default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: contactbook_development

test:
  <<: *default
  database: contactbook_test

production:
  <<: *default
  database: contactbook_production
  username: contactbook
  password: 1
